server:
  port: 8090


spring:
  datasource:

    url: jdbc:sqlserver://localhost\.:1433;database=XemTruyen2

    driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    username: sa
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
